#!/bin/sh
cubevar_app_name="myplaceonline"
cubevar_app_web_dir="/var/www/html/myplaceonline"
cubevar_app_db_host="db1-internal.myplaceonline.com"
cubevar_app_db_dbname="myplaceonline_production"
cubevar_app_db_dbuser="myplaceonline"
cubevar_app_server_name="myplaceonline.com"
cubevar_app_server_protocol="https"
cubevar_app_smtp_user="myplaceonline"
cubevar_app_mail_from="contact@myplaceonline.com"
cubevar_app_root_email="root@myplaceonline.com"
cubevar_app_tmpdir="/var/tmp/"
cubevar_app_full_text_search_target="db2-internal.myplaceonline.com:9200"
cubevar_app_networkping="104.236.182.29"
cubevar_app_rails_gc_max_newspace="33554432"
cubevar_app_rails_gc_max_oldspace="67108864"
cubevar_app_rails_threads_per_node="2"
cubevar_app_rails_environment="production"
cubevar_app_nginx_dir="/etc/nginx/"
cubevar_app_nginx_user="nginx"
cubevar_app_nginx_gzip_static="on"
cubevar_app_nginx_passenger_install_method="source"
cubevar_app_nginx_passenger_version="5.0.30"
cubevar_app_nginx_passenger_gem_binary="/usr/bin/gem"
cubevar_app_nginx_passenger_ruby="/usr/bin/ruby"
cubevar_app_nginx_passenger_root="/usr/local/share/gems/gems/passenger-5.0.30/"

# When updating nginx version, also update checksum in the next var
cubevar_app_nginx_source_version="1.11.6"
# wget https://nginx.org/download/nginx-1.11.6.tar.gz; sha256sum nginx-1.11.6.tar.gz;
cubevar_app_nginx_source_checksum="3153abbb518e2d9c032e1b127da3dc0028ad36cd4679e5f3be0b8afa33bc85bd"

cubevar_app_nginx_source_modules="nginx::ipv6 nginx::http_ssl_module nginx::http_gzip_static_module nginx::passenger nginx::upload_progress_module"
cubevar_app_postgresql_version="9.5"
cubevar_app_postgresql_replication_cluster="cluster1"
cubevar_app_keys_postgresql_public="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIaaOF750AA0A3/H/HxzO5Bje2zfPLjFEtnrBfn7/6hDa9jr95nAN2wyTAJz5Io+oPo11MTJBSVtQRbbj8UNExqEQubNv0SlmSbbIx6Mgh4QMgUeDh2dUVPetXN729KVUdLZFiaBAMf5hSRbO8DO5PFDwWKjPY1qBXnv/Y5+nw7N5upyN163Bo8r5DizzZ6Ow7zXXBWAd4uu7cV1qvkEO2+UeZyFj0pRZlgeury0Pi1eyoD6YLtQwkeJiKIjaz5+MUNwj51IgpBJR0bAHPQSsOIc9GgROoPR1MNZcOVwU6DPauEvtM0hxLk4Bj89vGp5lhaEKyzy/tCuqPKvQwS/DGBrS5yQ404x2IBIhD39XqTApU3zEKWjlbaePeGfNALLy6mmgMn9ppNI5dTuXfZj35uFDEP3Fdv8x5vJXucIM+I+LzGVyebB3tjsbfq/G8Kdoeoqpq6+oTDIF8iSVbndoRY5xwUSXPy3Os72n16dBj9BxhlihBPV8mGOlgmK91fpmAsYwXsjFNFhjm8YlJm6rXcK32WFC6wewNa+kbvHa+/guIGjVYjUk+fmrUDrNzQ4GZ8k6VgslpxF5uR5QY0oJT6mN47/eNoAh2KkKHFPVa/3t+0I0KnyKMeTuWkJ3no6WjHOfbWY21qmha4AiDFm8r3JRR2xA4iiIIAvFQ+XG6rQ=="
cubevar_app_nfs_client_mount="/var/lib/remotenfs/"
cubevar_app_nfs_client_mount_backup="/var/lib/remotenfs_backup/"
cubevar_app_nfs_client_host="db1-internal.myplaceonline.com"
cubevar_app_nfs_server_directory="/var/lib/nfsshare/"
cubevar_app_influxdb_url="http://admin-internal.myplaceonline.com:8086"
cubevar_app_syslog_serverhost="db2-internal.myplaceonline.com"
