#!/bin/sh
cubevar_app_name="myplaceonline"
cubevar_app_web_dir="/var/www/html/myplaceonline"
cubevar_app_db_host="db5-internal.myplaceonline.com"
cubevar_app_db_dbname="myplaceonline_production"
cubevar_app_db_dbuser="myplaceonline"
cubevar_app_server_name="myplaceonline.com"
cubevar_app_server_protocol="https"
cubevar_app_smtp_user="myplaceonline"
cubevar_app_mail_from="contact@myplaceonline.com"
cubevar_app_root_email="root@myplaceonline.com"
cubevar_app_tmpdir="/var/tmp/"
cubevar_app_full_text_search_target="db6-internal.myplaceonline.com:9200"
cubevar_app_rails_gc_max_newspace="33554432"
cubevar_app_rails_gc_max_oldspace="67108864"
# Assume about 400MB per thread
cubevar_app_rails_threads_per_node="3"
cubevar_app_rails_environment="production"
# Updating this causes a recompile. See available versions at https://nginx.org/download/
cubevar_app_nginx_source_version="1.13.1"
cubevar_app_postgresql_replication_cluster="cluster2"
cubevar_app_keys_postgresql_public="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIaaOF750AA0A3/H/HxzO5Bje2zfPLjFEtnrBfn7/6hDa9jr95nAN2wyTAJz5Io+oPo11MTJBSVtQRbbj8UNExqEQubNv0SlmSbbIx6Mgh4QMgUeDh2dUVPetXN729KVUdLZFiaBAMf5hSRbO8DO5PFDwWKjPY1qBXnv/Y5+nw7N5upyN163Bo8r5DizzZ6Ow7zXXBWAd4uu7cV1qvkEO2+UeZyFj0pRZlgeury0Pi1eyoD6YLtQwkeJiKIjaz5+MUNwj51IgpBJR0bAHPQSsOIc9GgROoPR1MNZcOVwU6DPauEvtM0hxLk4Bj89vGp5lhaEKyzy/tCuqPKvQwS/DGBrS5yQ404x2IBIhD39XqTApU3zEKWjlbaePeGfNALLy6mmgMn9ppNI5dTuXfZj35uFDEP3Fdv8x5vJXucIM+I+LzGVyebB3tjsbfq/G8Kdoeoqpq6+oTDIF8iSVbndoRY5xwUSXPy3Os72n16dBj9BxhlihBPV8mGOlgmK91fpmAsYwXsjFNFhjm8YlJm6rXcK32WFC6wewNa+kbvHa+/guIGjVYjUk+fmrUDrNzQ4GZ8k6VgslpxF5uR5QY0oJT6mN47/eNoAh2KkKHFPVa/3t+0I0KnyKMeTuWkJ3no6WjHOfbWY21qmha4AiDFm8r3JRR2xA4iiIIAvFQ+XG6rQ=="
cubevar_app_nfs_client_mount="/var/lib/remotenfs/"
cubevar_app_nfs_client_mount_backup="/var/lib/remotenfs_backup/"
cubevar_app_nfs_client_host="db5-internal.myplaceonline.com"
cubevar_app_nfs_server_directory="/var/lib/nfsshare/"
cubevar_app_influxdb_url="http://db6-internal.myplaceonline.com:8086"
cubevar_app_syslog_serverhost="db6-internal.myplaceonline.com"
cubevar_app_syslog_serverhost_public="db6.myplaceonline.com"
cubevar_app_grafana_host="grafana.myplaceonline.com"
cubevar_app_web_init_timeout="60"
cubevar_app_primary_host_web_public="web4.myplaceonline.com"
cubevar_app_primary_host_db_public="db5.myplaceonline.com"
cubevar_app_backup_host_db_public="db6.myplaceonline.com"
cubevar_app_test_user="user1"
cubevar_app_letsencrypt_tls_domains="-d myplaceonline.com -d www.myplaceonline.com -d roamancers.com -d www.roamancers.com"
cubevar_app_tls_domains="myplaceonline.com roamancers.com"
